name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - run: mkdir -p ~/.local/state/nix/profiles
      - name: Build HM environment
        run: nix run home-manager/release-23.05 -- build --flake .#etienne
