name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        setup:
          - os: ubuntu-latest
            target: etienne
          - os: macos-latest
            target: etienne
          - os: ubuntu-latest
            target: etienne@delpech
    runs-on: ${{ matrix.setup.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          determinate: true
      - run: mkdir -p ~/.local/state/nix/profiles
      - name: Build HM environment
        run: nix run home-manager/release-23.05 -- build --flake .#${{ matrix.setup.target }}
